---
title: "Algebra and Pre-Calculus"
subtitle: "Day 2 AM"
author: "Sarah Moore"
institute: "Northwestern University"
date: "Math Camp 2023"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      
---

```{r xaringan-themer, include = F}
library(xaringanthemer)
style_solarized_light(header_font_google   = google_font("Roboto"),
  text_font_google   = google_font("Work Sans", "300", "300i"),
  code_font_google   = google_font("IBM Plex Mono")
  )
```

# Day 2 Agenda

-   Algebraic Properties

-   Inequalities and other relational operations

-   Functions and Relations

-   Exponents and Logarithms

---

# Algebraic Properties

1.  **Associative property** $(a+b)+c=a+(b+c)$ and $(a\times b)\times c=a\times (b \times c)$

2.  **Commutative property** $a+b=b+a$ and $a\times b=b\times a$

3.  **Distributive property** $a(b+c)=ab+ac$

4.  **Identity property** $x+0=x$ and $x\times 1=x$

5.   **Inverse property** $-x+x=0$.

Multiplicative inverse exists, but not for all numbers $x^{-1}\times x=1$

---
# Factoring

We may need to break down different functions.


$x^2+3x-4= (x-1)(x-4)$

$m^2+3m+2= (m+1)(m+2)$

$x^2+5x+6= (x+3)(x+2)$

$2x^2+7x+3 =(2x+1)(x+3)$

---
# Intervals and Inequalities 

## Intervals and Inequalities
Ranges of numbers can be expressed with either \[\] or \(\) brackets. 

Notation |      Meaning     |    Explanation 
---------|----------------- |------------------------------------
$[a,b]$  | $a \leq x \leq b$|Inclusive of end points (closed interval)
$(a,b)$  | $a < x < b$      |Exclusive of end points (open interval)
$\{a,b\}$|                  |Typically used for sets -- not inequalities/intervals


---
# Relational Expressions 

- $4 < x$ 

- $y>12$

- $3 <z <7$

- $(3,9)$

- $[-7,2)$

---

# Absolute Value

Magnitude of a numerical value indicated by $|x|$. Solved by typical arithmetic, but must solve for both the negative and positive equations.

For example: 

$$|x + 4| < 5 $$

>- Must be solved as: $-x-4<5$ AND $x+4<5$

Therefore:

>- $-9<x<1$  *Notice how the inequality was flipped due to the negative equation* 

>- Try this one out: $|\frac{x+2}{x}|<10$

>- Answer: $-\frac{2}{11} > x > \frac{2}{9}$

---

# Relations

Relations generally allow comparison of variables and expressions between a \textit{range (y)} and \textit{domain (x)}. 

You may be familiar with the term *functions*, which are a type of relation. These are the most common relation you will encounter in statistical social science; while *correspondences* are a type of relation more likely found in game theory. 

---
# Functions

Mathematical functions have certain constitutive parameters. 

>- Specifically, functions assign *one* element of the *range (y)* to each element of the *domain (x).*

---
# Relating Sets to Functions 

>- Domain: "the set of elements over which the function is defined" 

>- Co-Domain: "the set from which values of f(x) may be drawn" 

>- Range: "the set of all values actually reached", a subset of the co-domain 

>- Thinking back to day 2: In social sciences, these sets will all typically be composed of $\mathbb{R}$, i.e. the set of all real numbers. 
---
# Mapping Functions 

We might use some functional mapping to discern whether or not a relation constitutes a function:  

\begin{figure}[ht]
\centering
\begin{tikzpicture}
    % draw the sets
    \filldraw[fill=blue!20, draw=blue!60] (-1.5,0) circle (1cm);
    \filldraw[fill=red!20, draw=red!60] (1.5,0) circle (1cm);

    \node at (-1.5,1.5) {$X$};
    \node at (1.5,1.5) {$Y$};

    \node (x1) at (-1.5,0.7) {$a$};
    \node (x2) at (-1.5,0.3) {$b$};
    \node (x3) at (-1.5,-0.2) {$c$};
    \node (x4) at (-1.5,-0.7) {$d$};
    \node (y1) at (1.5,0.7) {$1$};
    \node (y2) at (1.5,0.3) {$2$};
    \node (y3) at (1.5,-0.2) {$3$};
    \node (y4) at (1.5,-0.7) {$4$};

    \draw[->] (x1) -- (y4);
    \draw[->] (x2) -- (y2);
    \draw[->] (x3) -- (y1);
    \draw[->] (x4) -- (y3);

\end{tikzpicture}
\caption{Mapping Relation $S$}
\end{figure}

[Source Code](https://tex.stackexchange.com/questions/19987/drawing-a-bijective-map-with-tikz)

So if functions requiring that there is only one range element for each domain, does this mapping constitute a function? 
---
# More Function Mapping 

Let's try out a couple more maps to see whether or not they are functions: 

\begin{figure}[ht]
\centering
\begin{tikzpicture}
    % draw the sets
    \filldraw[fill=blue!20, draw=blue!60] (-1.5,0) circle (1cm);
    \filldraw[fill=red!20, draw=red!60] (1.5,0) circle (1cm);

    \node at (-1.5,1.5) {$X$};
    \node at (1.5,1.5) {$Y$};

    \node (x1) at (-1.5,0.7) {$a$};
    \node (x2) at (-1.5,0.3) {$b$};
    \node (x3) at (-1.5,-0.2) {$c$};
    \node (x4) at (-1.5,-0.7) {$d$};
    \node (y1) at (1.5,0.7) {$1$};
    \node (y2) at (1.5,0.3) {$2$};
    \node (y3) at (1.5,-0.2) {$3$};
    \node (y4) at (1.5,-0.7) {$4$};

    \draw[->] (x1) -- (y1);
    \draw[->] (x2) -- (y2);
    \draw[->] (x2) -- (y3);
    \draw[->] (x2) -- (y4);
    \draw[->] (x3) -- (y2);
    \draw[->] (x4) -- (y1);

\end{tikzpicture}
\caption{Mapping Relation $H$}
\end{figure}

\pause 
Relation $H$ is not a function. 
---
# Functions

## Vertical Line Test 
Functions can only assign one x to one y. But sometimes our domain and range are not clearly defined and we may only have a graph immediately available to us. If any vertical line will pass through more than 1 point on the graph, then the relation is not a function. 

---
# Vertical Line Test

For example, based on the vertical line test which of the following graphs is not of a function: 

\centering 
\begin{tikzpicture}[scale=0.50]
    \begin{axis}[
        axis lines = middle,
        xmin=-3, xmax=3, ymin=-3, ymax=3,
        axis equal,
        xlabel = $x$,
        ylabel = {$f(x)$},
        yticklabels={,,}
        ]
        \draw (axis cs: 0,0) circle [radius=2];
    \end{axis}
\end{tikzpicture}
\hspace{2cm}
\begin{tikzpicture}[scale=0.50]
\begin{axis} [axis lines = middle]
\addplot{(x)^2};
\end{axis}
\end{tikzpicture}

---
# Types of Functions

>- Identity function-- Elements in domain are mapped to identical elements in codomain 
 
>- Inverse function-- Function that when composed with original function returns identity function

>- Surjective-- Every value in codomain produced by value in domain

>- Injective (one-to-one)-- Each value in range comes from only one value in domain

>- Bijective (invertible)-- Both surjective and injective; function has an inverse

---
# Monotonic Function Terms 

\footnotesize

\begin{center}
\begin{tabular}{ | l p{7.15 cm}| }  \hline
 Term & Meaning \\ \hline 
Increasing & Function increases on subset of domain \\
Decreasing & Function decreases on subset of domain \\
Strictly increasing & Function always increases on subset of domain \\
Strictly decreasing & Function always decreases on subset of domain \\
Weakly increasing & Function does not decrease on subset of domain \\
Weakly decreasing & Function does not increase on subset of domain \\
(Strict) monotonicity & Order preservation; function (strictly) increasing or decreasing over domain \\ \hline
\end{tabular}
\end{center}



\tiny Table 3.2 from Moore and Siegel (pg 51) \footnotesize \vspace{3mm}

---

# Why is understanding functional behavior important? 

Obviously useful to understand a function's behavior mathematically-- i.e. to understand how the input relates to the output over the function. 

*BUT* this is where we link some of the logic of math to theory construction. Ultimately you will choose what mathematical functions likely describe the relationship between x and y. 

Therefore, we need to know how to model these things functionally. 

---
# Linear Equation versus Linear Function 

- Thus far, we have addressed functions that are also linear equations -- in that the highest power of the argument $x$ is 1. 

- *Linear functions* are a broader category of functions, to potentially include linear equations, that follow the rules of additivity and scaling: 

  - Additivity: $f(x_1+x_2)= f(x_1)+f(x_2)$

  - Scaling: $f(ax)= af(x)$ for all $a$ 
  
- Ultimately this is mathematical definition rarely followed by social scientists. But, for the purposes of further reading for some of you all the distinction will be important. 
---
# Nonlinear Functions 

- More widely applicable is the differentiation between linear and non-linear functions. 

- Generally a function is nonlinear when it is not linear and does not meet the properties of scalability or additivity. 

Why does this matter?

- Up until now, the functions we've addressed assume a *linear* relationship between our x and y. But what if we have theoretical inclination to believe that the relationship is *nonlinear*-- what if there is a ceiling effect to our x or diminishing returns? 

- We need to be able to eventually account for these issues in our models, therefore, we must know how to model them mathematically. 

---

# Exponents

>- Multiplying a number by itself: $x*x*x*x=x^4$

>- Add or subtract exponents when multiplying same variable: $x^4*x^{-3}=x$ 

>- Simplify bases when same exponent: $x^4*y^4=(xy)^4$ and $m^{-2}n^2=(m^{-1}n)^2$

>- Power of power: multiply, $(x^3)^3=x^{3*3}=x^9$  \pause 

\textbf{Try}: $xz^2(x^3z^{-2})^3$ \pause  \textbf{=($xz^2(x^9z^{-6}))$}\pause \textbf{=$x^{10}z^{-4}$}
---
## Exponents 

Exponents are where you take a variable to some power -- e.g. $x^a$ where $x$ is a variable and $a$ is a constant. Typically, we focus on the numerical portion of the exponent--calling it `the exponent'. 


## Exponential 

An exponential is the reverse of the exponent -- here it is a number to the power of a variable, e.g. $a^x$. To get the $x$ `down', we need to use logarithms (aka logs). 

## Exponential Function
The exponential function has a particular base, $e$, (where $e$ is Euler's $e$ and is approx 2.72.)

---

# Higher Order Functions 

- Higher order polynomials refer to functions whose degree is greater than 1, thus entail a greater degree than a linear polynomial. 

- Quadratic polynomial: in the form $f(x)=ax^2+bx+c$, wherein the highest power is 2 

- Higher order polynomials: entail a degree higher than 2-- can be 3 or greater (unlikely, but could be there!)

---

# Logarithms 

Logarithms, or logs, are the inverses of exponents: the power to which you raise the base, e.g. 10, to produce a given value, e.g.$z$ \pause

Logarithms (typically base 10 ($log(x)$) or base $e$ ($ln(e)$), but any base is possible, e.g. $log_{8675309} x$ (Bases aside from $e$ and $10$ will be specified).

- $y=log(z) \leftrightarrow 10^y=z$

- $y=ln(z) \leftrightarrow e^y=z$

- $log(1)=0$

---

# Exponents and Logs 

Exponents in log are different from what you might expect:

-   $log(x^2)=2(log(x))$

-   $log (x/y)=log(x)-log(y)$ provided ($x,y >0$)

Logs help weigh smaller values more heavily; adding units not linear--less meaningful for larger values ($log(100)=2, log(1000)=3$).

---
# Logs Practice Simplify the following

 $log(x^4)$ 
 $log(xy)$ 
 $ln(e^3)$ 
 $ln(1)$ 
 $log(3)+log(7)$ 

---
# Logs Practice Simplify the following

 $log(x^4)$ \only<2->{$=4log(x)$}
 $log(xy)$ \only<3->{$=log(x)+log(y)$}
 $ln(e^3)$ \only<4->{$=3$}
 $ln(1)$ \only<5->{$=0$}
 $log(3)+log(7)$ \only<6->{$=log(21)$}


---
# Graphical Behavior 

\begin{figure}
\caption{Graph of $x^3$}
\begin{tikzpicture}[scale=0.75]
\begin{axis} [ axis lines* = middle]
\addplot [domain=-5:5]{(\x)^3};
\end{axis}
\end{tikzpicture}
\end{figure}

---
# Graphical Behavior 

\begin{figure}
\caption{Graph of $\frac{ln(x)}{ln 2}$}
\begin{tikzpicture}[scale=0.75]
\begin{axis}[axis lines* = middle]
\addplot [domain=-1:5]{ln(x)/ln(2)};
\end{axis}
\end{tikzpicture}
\end{figure}

[Source Code]((https://tex.stackexchange.com/questions/19608/plot-a-function-of-a-binary-logarithm-with-tikz))

---
# Graphical Behavior 

\begin{figure}
\caption{Graph of $\sqrt{x}$}

\begin{tikzpicture}[scale=0.75]
\begin{axis} [ axis lines* = middle]
\addplot [domain=-1:4]{(\x)^.5};
\end{axis}
\end{tikzpicture}
\end{figure}

---
# Functional Continuity

As we will discuss in the coming days, and especially if you go further along in methods courses, functional continuity is also a source of concern. 

- Some functions have certain points at which they *do not exist*. 

- On one hand, there could be a certain reason that the function breaks at a certain $x$ value. 

- In other cases, there are limiting properties of certain function such that the function cannot exist over a certain interval. 

- We won't go into more detail here, just know **continuity** and the interval we expect a function to exist over is important to understand conceptually. 

---
# Introduction to Matrices

A matrix is way of aggregating data by $n$ rows and $d$ columns. We can liken matrices to datasets in that rows data is organized into observations (rows) by columns (variables). 

---
# Introduction to Matrices

Matrices are described based on their $n \times d$ dimensions, that is the number of rows $\times$ columns in the matrix.

Matrices may be characterized by their specific shape. For example, a matrix with an equal number of rows and columns is a square matrix. Otherwise, a matrix is rectangular. 

\begin{columns}

\column{0.5\textwidth}
Square Matrix: 

\[
\begin{bmatrix}
a & b & c \\ 
1 & 0 & 0 \\ 
4 & 8 & 5 \\
\end{bmatrix}
\]

\column{0.5\textwidth}
Rectangular Matrix: 

\[
\begin{bmatrix}
a & b & c & d \\ 
1 & 0 & 0 & 1 \\ 
\end{bmatrix}
\]

\end{columns}

---
# Indexing Data in Matrices 

Like variables matrices are given names. Matrix names are typically capital letters like **$A, B, X, I, \Phi$**. Matrix elements are referenced by the matrix name and the element's row and column number. Generally, this is shown by $a_{i,j}$. 

Suppose we have the following matrix. What are the dimensions of matrix $[B]$ below, and what value is $b_{23}$?

\[
\begin{bmatrix}
3&2&8&11&14&19 \\
9& 81 & 21& 31& 41& 1 \\
13& 7 & 6 & 4 & 5 & 20
\end{bmatrix}
\]

\pause Dimensions are 3 x 6; $b_{23}$ is 21. 

---
# Elements of Matrices

The elements along the diagonal often are important in matrices. We typically focus upon the diagonal that starts in the upper left and goes down to the lower right. 

\[
[A]=\begin{bmatrix}
1 & 3 & 5 \\
0 & 2 & 4 \\
0 & 0 & 6
\end{bmatrix} 
[B]=
\begin{bmatrix}
1 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 6
\end{bmatrix}
[C]=
\begin{bmatrix}
1 & 0 & 0 \\
3& 2 & 0 \\
5& 4 & 6
\end{bmatrix}
[D]=
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0& 0 & 1
\end{bmatrix}
\]


---

# Types of Matrices

We won't get into the details of all sorts of different matrices but it might be helpful to know that there are "special" matrices:

\small 

- Vector Matrices: only one row (row vector) or column (column vector)

- Submatrix: subset of a matrix

- Triangular Matrix: part of matrix is zeros -- all bottom triangle zeros is upper triangular, all upper triangle zeros is lower triangular.

- Diagonal Matrix: only the diagonal is non-zero

- Zero Matrix: everything is zeros

- Identity Matrix ($I$): all zeros except on diagonal AND diagonal is only ones, this is the matrix version of multiplying by 1

- Transpose ($[A]^T$): This is where you flip all the rows/columns. Meaning, if something was row 3, col 2, it will now be row 2, col 3. Done by `reflecting' over the main diagonal (so the diagonal stays the same)

---

# Identifying Matrices
Define the kinds of matrices below: 

\[
[A]=\begin{bmatrix}
1 & 3 & 5 \\
0 & 2 & 4 \\
0 & 0 & 6
\end{bmatrix} 
[B]=
\begin{bmatrix}
1 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 6
\end{bmatrix}
[C]=
\begin{bmatrix}
1 & 0 & 0 \\
3& 2 & 0 \\
5& 4 & 6
\end{bmatrix}
[D]=
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0& 0 & 1
\end{bmatrix}
\]

\pause

\textit{A: Upper triangular, B: Zero matrix, C: Lower triangular, D: Identity matrix; Fun fact! A and C are the transpose of each other}

---

# Adding matrices

Adding and subtracting matrices requires that you have matrices that have the same dimensions as each other. You then add the elements together (or subtract, as applicable). The resulting matrix will have the same dimension as the originals. 

\[
 \begin{bmatrix}
1 & 13 & 15 \\
2 & 4 & 6 
\end{bmatrix}
+
\begin{bmatrix}
2 & 4 & 6 \\
1 & 3 & 5 
\end{bmatrix}
=
\begin{bmatrix}
3 & 17 & 23 \\
3 & 7 & 13 
\end{bmatrix}
\]

\[
 \begin{bmatrix}
1 & 13 & 15 \\
2 & 4 & 6 
\end{bmatrix}
-
\begin{bmatrix}
2 & 4 & 6 \\
1 & 3 & 5 
\end{bmatrix}
=
\begin{bmatrix}
-1 & 9 & 9 \\
1 & 1 & 1 
\end{bmatrix}
\]

---

# Multiplying Matrices

>- Just like in every other matrix operation, before you multiply matrices you must define their dimensions. To determine if you *can* multiply matrices, you need the number of **COLUMNS** in the matrix 1 to be the same as the number of **ROWS** in matrix 2. 

>- You can't swap matrix positions like in regular multiplying. A$\times$B is not the same as B$\times$A. 

>- Let's think about what you *should* end up with. You will end up with a matrix equal to the number of ROWS in the FIRST matrix and the number of COLUMNS in the SECOND matrix. For example, $A_{2\times3}\times B_{3\times3}$ will return a matrix $C_{2\times3}$

>- Now the math gets a bit weird. You go ACROSS the first row of the matrix and multiply it DOWN the first column of the second matrix. Repeat this across each row, column pair.  

---

# Matrix Multiplication

If you have a matrix setup like this: $A_{rxs} \times B_{sxt}$ then you will get a matrix that is $C_{r \times t}$.
---

# Matrix Multiplication Example 

\[
[A]=\begin{bmatrix}
7 & 8  
\end{bmatrix} 
[B]=
\begin{bmatrix}
2 & 4 & 6 \\
1 & 3 & 5 \\
\end{bmatrix}
\]
 

Let's multiply! You take the row of the first matrix, multiply it by the COLUMN (hence the need to match) of the second matrix, ADD the sum of these products, and that goes into the first cell of the `final' matrix. Then you do the same thing for the next column. 
\pause
So, here, it would be: 
\[
[C]=\begin{bmatrix}
7*2+8*1  & 7*4 + 8*3 & 7*6+8*5
\end{bmatrix}
\] 
Note this is a row vector: $[C]=\begin{bmatrix}22 & 52 & 82\end{bmatrix}$
---
# Multiplying Matrices
If you have multiple rows in your initial matrix, you just do the same process over again, following the same procedure for each row. Your final matrix will have dimensions determined in the same way. For example, if you have a 2 x 3 and a 3 x 3, you'll have a 2 x 3 as your resulting matrix. \pause

\[
[A]=\begin{bmatrix}
7 & 8  \\
1 & 2
\end{bmatrix} 
[B]=
\begin{bmatrix}
2 & 4 & 6 \\
1 & 3 & 5 \\
\end{bmatrix}
\]

\pause
\[
[C]=\begin{bmatrix}
7*2+8*1  & 7*4 + 8*3 & 7*6+8*5 \\
1*2+2*1 & 1*4 + 2*3 & 1*6+2*5
\end{bmatrix}
=\begin{bmatrix}
22 & 52 & 82 \\
4 & 10 & 16
\end{bmatrix}
\] 
---
# Multiplying Matrices: Practice
\[
[A]=
\begin{bmatrix}
1 & 3 & 4 \\
2 & 2 & 8 \\
\end{bmatrix}
[B]=
\begin{bmatrix}
1 & 3 & 5 \\
0 & 2 & 4 \\
0 & 0 & 6
\end{bmatrix} 
[C]=
\begin{bmatrix}
1 & 0 & 0 \\
3& 2 & 0 \\
5& 4 & 6 \\
1 & 1 & 1
\end{bmatrix}
[D]=
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0& 0 & 1
\end{bmatrix}
\]

Try the following: 
\begin{itemize}
\item \textbf{A x B}
\item \textbf{B x A}
\item \textbf{A x C}
\item \textbf{B x D}
\end{itemize}
---
# Answers 
\begin{itemize}
\item \textbf{A x B} $\begin{bmatrix} 1 & 9 & 41 \\ 2 & 10& 46\end{bmatrix}$
\item \textbf{B x A} Not possible: 3 x 3 and 2 x 3 (middle numbers must match)
\item \textbf{A x C} Not possible: 2 x 3 and 4 x 3 (middle numbers must match)
\item \textbf{B x D} B (D is the identity matrix so you always get back whatever you multiplied it by)
\end{itemize}
---
# Matrices: A Rundown 

- Dimensions matter. Different operations place different restrictions on dimensionality. 

- Multiplying matrices does not happen how you would think. Take a minute to think through what matrix multiplication requires. 

- Different types of matrices (especially the transpose and the identity matrices) will become more relevant later on. Remember these! 

- Dividing matrices is even more weird. That's what calculators are for.... 
---
# Summation 
Using sums can help us when we're summing a large number of items or when summing more complex functions. 

 Summation rules:
 \pause
 \begin{enumerate}
 \item $\sum_{n=1}^{k} c=kc$ where c is a constant
\pause
 \item $\sum_{n=1}^{k} n=\frac{k(k+1)}{2}$
\pause 
 \item $\sum_{n=1}^k 4+3n=\sum_{n=1}^k 4 + 3\sum_{n=1}^k n=4k+ 3\frac{k(k+1)}{2}$
 \end{enumerate}
 \pause
 \vspace{2mm}
 Try:
 
  $\sum_{n=1}^{5} 6$\uncover<5->{  Ans: $6*5=30$}    \hspace{6mm}        $\sum_{n=1}^{4} 2n+3$\uncover<6->{  Ans: $2*(4*5)/2+3*4=32$}
---
# Some Additional Definitions with Summation

- The following section is a bit abstract, but contains some algebraic concepts we set aside for those that might like to learn about formal theory later on.

- It will also be helpful to move on to our next section on *limits*. 
---
# Sequences and Series

## Sequences 
A sequence is an ordered list of numbers. They can be infinite or finite, but all are \textit{countable}. Written ${x_i}^N_{i=1}$

## Series 
A series is the sum of a sequence, written $\Sigma^N_{i=1}x_i$. 

---

# Sequences 

- We refer to the elements of a sequence by their position. For example, the third element would be $x_3$.

- A sequence is generated and represented by some equation wherein each element is a function of the element preceding it. 

- Take the following sequence: $\{1, 2, 5, 26, 677...\}$. This sequence is defined by the following generating equation:$$ \{x_i^2+1\}_{i=1}^\infty$$

- Some sequences are *infinite*, as the sequence above. Others are *finite* and will end at the $n$th term. 

---
# Series 

- A series will essentially take a sequence and add together each of the numbers, such that our example sequence from the previous slide becomes: $\{1+  2+ 5 + 26 + 677...\}$. 

- Infinite series will sum to $\infty$ given that they are infinite! Shocking! However, we might also specify to know the sum at a given $n$ term. In which case I would probably just tell you to look up a calculator to do it for you.  

- Finite sums can more easily be summed, again likely with a calculator if $N$ is sufficiently large. 

---
# Limits

The sums, sequences, and functions we have visited over the last couple of days all have *limits*. 

Particularly related to series, we say that these series **converge** while those series that just keep getting bigger and bigger and bigger (or smaller, etc.) **diverge**. 


$$lim_{N\rightarrow\infty} \sum_{i=1}^N x_i=S$$

Translation: The limit of the sum $x_i$ from $i$ to N as N approaches infinity is S. 


We can talk in the same way about sequences $lim_{i\rightarrow\infty}x_i=L$. 

---

# Limits

When we turn to functions, asking about the limit at a particular point asks: 

"What is the slope of the line at this infinitesimally tiny part of the line?"

$lim_{i\rightarrow\infty}f(x)=L$


A second way to ask this is to look at what happens to the slope as as the distance between points approaches zero. However, to actually calculate the derivative, we need to first be sure that the point is differentiable. Again, we will use limits.

---
# Differentiation

To differentiate a function, it must be *continuous* on the *interval*. 

Some functions are not differentiable or not differentiable at a certain point.

A function is continuous if:

- Limit exists 

- Limit from left equals limit from right 

- These limits equal the value at the point

---

# Limits

For us, you should be able to:

- Plug a value in to the limit and see what you get out (check for dividing by zero).

- Recognize an indeterminate limit: $\frac{0}{0}$ or $\frac{\infty}{\infty}$ 

- Compare powers in an indeterminate limit to find what happens: Same degree: limit goes to whatever fraction you get when you divide the top and bottom first terms 

Try: 
$$lim_{x\rightarrow4} \frac{x+2}{x+5}$$

$$lim_{x\rightarrow4} \frac{x^2-4}{x+2}$$


Ans: 6/9, simplifies to 2/3; simplifies to x-2; limit is 2. 

---

# What is calculus? 

- So basically, calculus is the study of *instantaneous change of a function*. 

*Well, what does that mean?* 

- On the one hand, we could be interested in *discrete* change. Discrete change tells us the difference between two points on a graph, thus the difference between two observations modeled by a function. 

- Finding discrete change means finding the slope of two points, or the *secant.* You all are probably familiar with $rise \over run$ from algebra. 

---

# What is calculus? 

- But, finding the secant has a limitation. Discrete change only tells about the functional behavior *over an interval*. Instead we might want to find the rate of change at a *very specific moment* in the function. 

- Consequently, we might also want to find extrema (min and max) of a function, any other critical points, or understand its shape. As you may remember from other courses, these are difficult tasks with merely a function $f(x)$. 

- Calculus gives us some tools to calculate instantaneous change and other downstream quantities. 
---

# Capturing Change 

- Today, we went over limits of functions. As a reminder, the limit of a function $f(x)$ at a given point $x$ is the value of the function as it approaches the given $x$. 

- Therefore, to capture discrete change we calculate the secant between two points by taking the difference of the functional limits, i.e. $f(x_2)- f(x_1)\over x_2-x_1$. 

---

# Capturing Change 

- To capture the instantaneous or continuous rate of change of a function, we *could* take the difference of the limits over iterations, making the interval between each $x$ smaller and smaller. 

\centering
\begin{tikzpicture}[scale=0.75]
\begin{axis} [ axis lines* = middle]
\addplot [domain=-1:4]{(\x)^2};
\addplot[color=red,mark=*] coordinates {
		(2,4)};
\draw[-to] (axis cs:1, 4) -- (axis cs:1.85, 4);
\draw[to-] (axis cs:2.15, 4) -- (axis cs:3,4);
\end{axis}
\end{tikzpicture}

- However, the concept of **tangents**, and consequentially **derivatives**, makes this easier. 

---
# Tangents and Derivatives 

- While a secant is a slope of a given line, a *tangent* is a line that touches the function at a given point. The tangent's slop can tell us about the slope of the primary function, or the instantaneous rate of change, *at that particular point*. 

- Therefore, the problem becomes *how to find the tangent's slope*. 



