---
title: "Matrix Algebra +"
subtitle: "Day 5 AM"
author: "Sarah Moore & J. Seawright"
institute: "Northwestern University"
date: "Math Camp 2023"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      
---

```{r xaringan-themer, include = F}
library(xaringanthemer)
style_solarized_light(header_font_google   = google_font("Roboto"),
  text_font_google   = google_font("Work Sans", "300", "300i"),
  code_font_google   = google_font("IBM Plex Mono")
  )
```
# Introduction to Matrices

A matrix is way of aggregating data by $n$ rows and $d$ columns. We can liken matrices to datasets in that rows data is organized into observations (rows) by columns (variables). 

---
# Introduction to Matrices

Matrices are described based on their $n \times d$ dimensions, that is the number of rows $\times$ columns in the matrix.

Matrices may be characterized by their specific shape. For example, a matrix with an equal number of rows and columns is a square matrix. Otherwise, a matrix is rectangular. 

\begin{columns}

\column{0.5\textwidth}
Square Matrix: 

\[
\begin{bmatrix}
a & b & c \\ 
1 & 0 & 0 \\ 
4 & 8 & 5 \\
\end{bmatrix}
\]

\column{0.5\textwidth}
Rectangular Matrix: 

\[
\begin{bmatrix}
a & b & c & d \\ 
1 & 0 & 0 & 1 \\ 
\end{bmatrix}
\]

\end{columns}

---
# Indexing Data in Matrices 

Like variables matrices are given names. Matrix names are typically capital letters like **$A, B, X, I, \Phi$**. Matrix elements are referenced by the matrix name and the element's row and column number. Generally, this is shown by $a_{i,j}$. 

Suppose we have the following matrix. What are the dimensions of matrix $[B]$ below, and what value is $b_{23}$?

\[
\begin{bmatrix}
3&2&8&11&14&19 \\
9& 81 & 21& 31& 41& 1 \\
13& 7 & 6 & 4 & 5 & 20
\end{bmatrix}
\]

\pause Dimensions are 3 x 6; $b_{23}$ is 21. 

---
# Elements of Matrices

The elements along the diagonal often are important in matrices. We typically focus upon the diagonal that starts in the upper left and goes down to the lower right. 

\[
[A]=\begin{bmatrix}
1 & 3 & 5 \\
0 & 2 & 4 \\
0 & 0 & 6
\end{bmatrix} 
[B]=
\begin{bmatrix}
1 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 6
\end{bmatrix}
[C]=
\begin{bmatrix}
1 & 0 & 0 \\
3& 2 & 0 \\
5& 4 & 6
\end{bmatrix}
[D]=
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0& 0 & 1
\end{bmatrix}
\]


---

# Types of Matrices

We won't get into the details of all sorts of different matrices but it might be helpful to know that there are "special" matrices:

\small 

- Vector Matrices: only one row (row vector) or column (column vector)

- Submatrix: subset of a matrix

- Triangular Matrix: part of matrix is zeros -- all bottom triangle zeros is upper triangular, all upper triangle zeros is lower triangular.

- Diagonal Matrix: only the diagonal is non-zero

- Zero Matrix: everything is zeros

- Identity Matrix ($I$): all zeros except on diagonal AND diagonal is only ones, this is the matrix version of multiplying by 1

- Transpose ($[A]^T$): This is where you flip all the rows/columns. Meaning, if something was row 3, col 2, it will now be row 2, col 3. Done by `reflecting' over the main diagonal (so the diagonal stays the same)

---

# Identifying Matrices
Define the kinds of matrices below: 

\[
[A]=\begin{bmatrix}
1 & 3 & 5 \\
0 & 2 & 4 \\
0 & 0 & 6
\end{bmatrix} 
[B]=
\begin{bmatrix}
1 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 6
\end{bmatrix}
[C]=
\begin{bmatrix}
1 & 0 & 0 \\
3& 2 & 0 \\
5& 4 & 6
\end{bmatrix}
[D]=
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0& 0 & 1
\end{bmatrix}
\]

\pause

\textit{A: Upper triangular, B: Zero matrix, C: Lower triangular, D: Identity matrix; Fun fact! A and C are the transpose of each other}

---

# Adding matrices

Adding and subtracting matrices requires that you have matrices that have the same dimensions as each other. You then add the elements together (or subtract, as applicable). The resulting matrix will have the same dimension as the originals. 

\[
 \begin{bmatrix}
1 & 13 & 15 \\
2 & 4 & 6 
\end{bmatrix}
+
\begin{bmatrix}
2 & 4 & 6 \\
1 & 3 & 5 
\end{bmatrix}
=
\begin{bmatrix}
3 & 17 & 23 \\
3 & 7 & 13 
\end{bmatrix}
\]

\[
 \begin{bmatrix}
1 & 13 & 15 \\
2 & 4 & 6 
\end{bmatrix}
-
\begin{bmatrix}
2 & 4 & 6 \\
1 & 3 & 5 
\end{bmatrix}
=
\begin{bmatrix}
-1 & 9 & 9 \\
1 & 1 & 1 
\end{bmatrix}
\]

---

# Multiplying Matrices

>- Just like in every other matrix operation, before you multiply matrices you must define their dimensions. To determine if you *can* multiply matrices, you need the number of **COLUMNS** in the matrix 1 to be the same as the number of **ROWS** in matrix 2. 

>- You can't swap matrix positions like in regular multiplying. A$\times$B is not the same as B$\times$A. 

>- Let's think about what you *should* end up with. You will end up with a matrix equal to the number of ROWS in the FIRST matrix and the number of COLUMNS in the SECOND matrix. For example, $A_{2\times3}\times B_{3\times3}$ will return a matrix $C_{2\times3}$

>- Now the math gets a bit weird. You go ACROSS the first row of the matrix and multiply it DOWN the first column of the second matrix. Repeat this across each row, column pair.  

---

# Matrix Multiplication

If you have a matrix setup like this: $A_{rxs} \times B_{sxt}$ then you will get a matrix that is $C_{r \times t}$.
---

# Matrix Multiplication Example 

\[
[A]=\begin{bmatrix}
7 & 8  
\end{bmatrix} 
[B]=
\begin{bmatrix}
2 & 4 & 6 \\
1 & 3 & 5 \\
\end{bmatrix}
\]
 

Let's multiply! You take the row of the first matrix, multiply it by the COLUMN (hence the need to match) of the second matrix, ADD the sum of these products, and that goes into the first cell of the `final' matrix. Then you do the same thing for the next column. 
\pause
So, here, it would be: 
\[
[C]=\begin{bmatrix}
7*2+8*1  & 7*4 + 8*3 & 7*6+8*5
\end{bmatrix}
\] 
Note this is a row vector: $[C]=\begin{bmatrix}22 & 52 & 82\end{bmatrix}$
---
# Multiplying Matrices
If you have multiple rows in your initial matrix, you just do the same process over again, following the same procedure for each row. Your final matrix will have dimensions determined in the same way. For example, if you have a 2 x 3 and a 3 x 3, you'll have a 2 x 3 as your resulting matrix. \pause

\[
[A]=\begin{bmatrix}
7 & 8  \\
1 & 2
\end{bmatrix} 
[B]=
\begin{bmatrix}
2 & 4 & 6 \\
1 & 3 & 5 \\
\end{bmatrix}
\]

\pause
\[
[C]=\begin{bmatrix}
7*2+8*1  & 7*4 + 8*3 & 7*6+8*5 \\
1*2+2*1 & 1*4 + 2*3 & 1*6+2*5
\end{bmatrix}
=\begin{bmatrix}
22 & 52 & 82 \\
4 & 10 & 16
\end{bmatrix}
\] 
---
# Multiplying Matrices: Practice
\[
[A]=
\begin{bmatrix}
1 & 3 & 4 \\
2 & 2 & 8 \\
\end{bmatrix}
[B]=
\begin{bmatrix}
1 & 3 & 5 \\
0 & 2 & 4 \\
0 & 0 & 6
\end{bmatrix} 
[C]=
\begin{bmatrix}
1 & 0 & 0 \\
3& 2 & 0 \\
5& 4 & 6 \\
1 & 1 & 1
\end{bmatrix}
[D]=
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0& 0 & 1
\end{bmatrix}
\]

Try the following: 
\begin{itemize}
\item \textbf{A x B}
\item \textbf{B x A}
\item \textbf{A x C}
\item \textbf{B x D}
\end{itemize}
---
# Answers 
\begin{itemize}
\item \textbf{A x B} $\begin{bmatrix} 1 & 9 & 41 \\ 2 & 10& 46\end{bmatrix}$
\item \textbf{B x A} Not possible: 3 x 3 and 2 x 3 (middle numbers must match)
\item \textbf{A x C} Not possible: 2 x 3 and 4 x 3 (middle numbers must match)
\item \textbf{B x D} B (D is the identity matrix so you always get back whatever you multiplied it by)
\end{itemize}
---
# Matrices: A Rundown 

- Dimensions matter. Different operations place different restrictions on dimensionality. 

- Multiplying matrices does not happen how you would think. Take a minute to think through what matrix multiplication requires. 

- Different types of matrices (especially the transpose and the identity matrices) will become more relevant later on. Remember these! 

- Dividing matrices is even more weird. That's what calculators are for.... 

---